### ISSUE TITLE
Override `ModelDeploymentSpec` of registered models 

### ISSUE THREAD

**Issue by spillai** [autonomi-ai/nos#518]
Right now, only custom models can be registered with a `ModelDeploymentSpec`. We need to support model definitions where the deployment spec overrides the existing model profile. 

```yaml
images:
  custom-gpu:
    base: autonomi/nos:latest-gpu
    env:
      NOS_MAX_CONCURRENT_MODELS: 2

models:
  TinyLlama/TinyLlama-1.1B-Chat-v1.0:
    runtime_env: custom-gpu
    deployment:
      resources:
        device: auto
        device_memory: 3Gi
```

- added limitation note in https://github.com/autonomi-ai/nos/pull/517
